In [48]:
import numpy as np
import pandas as pd

In [49]:
df1 = pd.DataFrame({
    "key1": ['a', 'a', 'b', 'b', 'a'],
    "key2": ['one', 'two', 'one', 'two', 'one'],
    "data1": np.random.randn(5),
    "data2": np.random.randn(5)
})

In [50]:
df1

  key1 key2     data1     data2
0    a  one  1.677814 -0.082796
1    a  two  1.544892 -0.321126
2    b  one -0.195839 -0.557372
3    b  two  0.159624 -2.580857
4    a  one -0.158444  0.126036

In [51]:
df1['data1'].groupby(df1['key1']).sum() # select sum(data1) from df1 group by key1

key1
a    3.064261
b   -0.036215
Name: data1, dtype: float64

In [52]:
grp1 = df1['data1'].groupby(df1['key1'])

In [53]:
grp1.sum()

key1
a    3.064261
b   -0.036215
Name: data1, dtype: float64

In [54]:
grp1.mean()

key1
a    1.021420
b   -0.018108
Name: data1, dtype: float64

In [55]:
grp2 = df1['data1'].groupby([ df1['key1'], df1['key2'] ])

In [56]:
df2 = grp2.mean()

In [57]:
df2.index

MultiIndex([('a', 'one'),
            ('a', 'two'),
            ('b', 'one'),
            ('b', 'two')],
           names=['key1', 'key2'])

In [58]:
df2

key1  key2
a     one     0.759685
      two     1.544892
b     one    -0.195839
      two     0.159624
Name: data1, dtype: float64

In [59]:
df3 = df2.unstack()

In [60]:
df3

key2       one       two
key1
a     0.759685  1.544892
b    -0.195839  0.159624

In [61]:
df3.index

Index(['a', 'b'], dtype='str', name='key1')

In [62]:
df3.columns

Index(['one', 'two'], dtype='str', name='key2')

In [63]:
df3

key2       one       two
key1
a     0.759685  1.544892
b    -0.195839  0.159624

In [64]:
grp2.size() # select count(*) from df1 group by key1, key2

key1  key2
a     one     2
      two     1
b     one     1
      two     1
Name: data1, dtype: int64

In [65]:
grp2

In [66]:
for key,value in grp2:
  k1,k2 = key
  print(k1, "\t", k2, "\t", str(value.iloc[0]))

a 	 one 	 1.6778139643626593
a 	 two 	 1.544891979756609
b 	 one 	 -0.19583921760393871
b 	 two 	 0.15962380298981266

In [67]:
df1

  key1 key2     data1     data2
0    a  one  1.677814 -0.082796
1    a  two  1.544892 -0.321126
2    b  one -0.195839 -0.557372
3    b  two  0.159624 -2.580857
4    a  one -0.158444  0.126036

In [68]:
grp3 = df1.groupby('key1')['data1']

In [69]:
grp4 = df1.groupby('key1')[['data1','data2']] # syntactic sugar
# grp4 = df1[['data1','data2']].groupby(df1['key1'])

In [70]:
grp5 = df1.groupby(['key1','key2'])[['data1','data2']] # syntactic sugar
#grp5 = df1[['data1','data2']].groupby([df1['key1'],df1['key2']])

In [71]:
columns = pd.MultiIndex.from_arrays([
     ['US', 'US', 'US', 'TR', 'TR'],
     [1,3,5,1,3]                                
], names= ['code','cty'])
df4 = pd.DataFrame(np.random.randn(4,5), columns= columns)

In [72]:
df4

code        US                            TR
cty          1         3         5         1         3
0    -0.696352 -0.787889 -1.646994  0.131450  1.061544
1    -1.311209  1.134733  0.281556  0.644599  0.518799
2    -0.213791  0.235529 -2.878940 -0.706660 -0.073660
3    -0.316914 -0.393460  0.069778 -1.000373 -0.118356

In [73]:
# Aggregation Methods
# 1. quantile
# 2. custom agg. function

In [74]:
df1 = pd.DataFrame({
    "key1": ['a', 'a', 'b', 'b', 'a'],
    "key2": ['one', 'two', 'one', 'two', 'one'],
    "data1": np.random.randn(5),
    "data2": np.random.randn(5)
})

In [75]:
df1

  key1 key2     data1     data2
0    a  one -1.113695 -0.573596
1    a  two  1.397593  1.127419
2    b  one  1.053118 -1.516097
3    b  two -0.840324 -0.271286
4    a  one -1.859288 -0.430447

In [76]:
grp6 = df1.groupby('key1')

In [77]:
df1.describe()

          data1     data2
count  5.000000  5.000000
mean  -0.272519 -0.332801
std    1.422533  0.949175
min   -1.859288 -1.516097
25%   -1.113695 -0.573596
50%   -0.840324 -0.430447
75%    1.053118 -0.271286
max    1.397593  1.127419

In [78]:
grp6['data1'].quantile(0.9)

key1
a    0.895335
b    0.863774
Name: data1, dtype: float64

In [79]:
def cust_agg1(arr):
  return arr.max() - arr.min()

In [80]:
grp6['data1'].agg(cust_agg1)

key1
a    3.256880
b    1.893442
Name: data1, dtype: float64

In [81]:
grp6['data1'].agg(lambda arr: arr.max() - arr.min())

key1
a    3.256880
b    1.893442
Name: data1, dtype: float64