In [70]:
# Data
# 1. Tabular -> i) RDBMS ii) JSON -> dictionary
# 2. Heterogeneous 
# Pandas -> NumPy

In [71]:
# Data 
#  i) Time Series (streaming data) -> network (http/websocket/...), kafka/rabbitmq/...
# ii) DataFrame (static data) -> file (json/csv/...), db, ...

In [72]:
# Pandas
# Time Series

In [73]:
import pandas as pd
import numpy as np
print("pandas version: ", pd.__version__)
print("numpy version: ", np.__version__)

pandas version:  3.0.3
numpy version:  2.4.5

In [74]:
ts1 = pd.Series([8, 24, 16, 4, 42])

In [75]:
ts1

0     8
1    24
2    16
3     4
4    42
dtype: int64

In [76]:
ts1.index

RangeIndex(start=0, stop=5, step=1)

In [77]:
ts1.values

array([ 8, 24, 16,  4, 42])

In [78]:
type(ts1.values)

numpy.ndarray

In [79]:
ts1[2]

np.int64(16)

In [80]:
ts1[1:3]

1    24
2    16
dtype: int64

In [81]:
ts2 = pd.Series([8, 24, 16, 4, 42], index=['a','b','c','d','e'])

In [82]:
ts2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

In [83]:
ts2

a     8
b    24
c    16
d     4
e    42
dtype: int64

In [84]:
ts2['b']

np.int64(24)

In [85]:
ts2['a':'d']

a     8
b    24
c    16
d     4
dtype: int64

In [86]:
ts1[[0,3,2]]

0     8
3     4
2    16
dtype: int64

In [87]:
ts1[ts1>16] ** 3

1    13824
4    74088
dtype: int64

In [88]:
np.sqrt(ts1[ts1>16])

1    4.898979
4    6.480741
dtype: float64

In [89]:
names = ['jack', 'kate', 'james']
'jack' in names

True

In [90]:
'ben' in names

False

In [91]:
'b' in ts2

True

In [92]:
'g' in ts2

False

In [93]:
ts2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

In [94]:
# how to create Series
ts1 = pd.Series([8, 24, 16, 4, 42])
ts2 = pd.Series([8, 24, 16, 4, 42], index=['a','b','c','d','e'])
population = {"turkey": 80_000_000, 'france': 70_000_000, 'italy': 60_000_000 }
ts3 = pd.Series(population) # key -> index, value -> values

In [95]:
ts3

turkey    80000000
france    70000000
italy     60000000
dtype: int64

In [96]:
ts3.index

Index(['turkey', 'france', 'italy'], dtype='str')

In [97]:
ts3.values

array([80000000, 70000000, 60000000])

In [98]:
ts3['turkey']

np.int64(80000000)

In [99]:
"turkey" in ts3

True

In [100]:
"japan" in ts3

False

In [101]:
# 2. DataFrame : tabular like tables in relational database

In [102]:
world = {
    'country': ['turkey', 'france', 'italy' ],
    'population': [80_000_000, 70_000_000, 60_000_000],
    'surface_area' : [120_000_000, 130_000_000, 90_000_000],
    'capital' : ['ankara', 'paris', 'rome'] 
}
df1 = pd.DataFrame(world)

In [103]:
df1

  country  population  surface_area capital
0  turkey    80000000     120000000  ankara
1  france    70000000     130000000   paris
2   italy    60000000      90000000    rome

In [104]:
df1.head(2)

  country  population  surface_area capital
0  turkey    80000000     120000000  ankara
1  france    70000000     130000000   paris

In [105]:
df1.tail(1)

  country  population  surface_area capital
2   italy    60000000      90000000    rome

In [106]:
df2 = pd.DataFrame(world, columns=["country","population"])

In [107]:
df2

  country  population
0  turkey    80000000
1  france    70000000
2   italy    60000000

In [108]:
df2.columns

Index(['country', 'population'], dtype='str')

In [109]:
df2.index

RangeIndex(start=0, stop=3, step=1)

In [110]:
df1['population']

0    80000000
1    70000000
2    60000000
Name: population, dtype: int64

In [111]:
df1.population

0    80000000
1    70000000
2    60000000
Name: population, dtype: int64

In [112]:
df1

  country  population  surface_area capital
0  turkey    80000000     120000000  ankara
1  france    70000000     130000000   paris
2   italy    60000000      90000000    rome

In [113]:
continents = pd.Series(['Asia','Europe','Europe'], index=[0,1,2])

In [114]:
df1['continent'] = continents

In [115]:
df1

  country  population  surface_area capital continent
0  turkey    80000000     120000000  ankara      Asia
1  france    70000000     130000000   paris    Europe
2   italy    60000000      90000000    rome    Europe

In [116]:
# How to remove a column from DataFrame
# del df1['continent']

In [117]:
df1['rich'] = df1.country != 'turkey'

In [118]:
df1

  country  population  surface_area capital continent   rich
0  turkey    80000000     120000000  ankara      Asia  False
1  france    70000000     130000000   paris    Europe   True
2   italy    60000000      90000000    rome    Europe   True

In [119]:
orders = {
    'symbol': ['orcl', 'msft', 'ibm' , 'goggl'],
    'price': [123.34, 98.23, 64.93, 143.56],
    'quantity' : [120, 130, 90, 200] 
}
df3 = pd.DataFrame(orders)

In [120]:
df3

  symbol   price  quantity
0   orcl  123.34       120
1   msft   98.23       130
2    ibm   64.93        90
3  goggl  143.56       200

In [121]:
df3['volume'] = df3.price * df3.quantity # vectorized + element-wise

In [122]:
df3

  symbol   price  quantity   volume
0   orcl  123.34       120  14800.8
1   msft   98.23       130  12769.9
2    ibm   64.93        90   5843.7
3  goggl  143.56       200  28712.0

In [123]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   symbol    4 non-null      str
 1   price     4 non-null      float64
 2   quantity  4 non-null      int64
 3   volume    4 non-null      float64
dtypes: float64(2), int64(1), str(1)
memory usage: 260.0 bytes

In [124]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country       3 non-null      str
 1   population    3 non-null      int64
 2   surface_area  3 non-null      int64
 3   capital       3 non-null      str
 4   continent     3 non-null      str
 5   rich          3 non-null      bool
dtypes: bool(1), int64(2), str(3)
memory usage: 255.0 bytes

In [125]:
df1.describe()

       population  surface_area
count         3.0  3.000000e+00
mean   70000000.0  1.133333e+08
std    10000000.0  2.081666e+07
min    60000000.0  9.000000e+07
25%    65000000.0  1.050000e+08
50%    70000000.0  1.200000e+08
75%    75000000.0  1.250000e+08
max    80000000.0  1.300000e+08

In [126]:
df3.describe()

            price    quantity        volume
count    4.000000    4.000000      4.000000
mean   107.515000  135.000000  15531.600000
std     33.908534   46.547467   9587.133845
min     64.930000   90.000000   5843.700000
25%     89.905000  112.500000  11038.350000
50%    110.785000  125.000000  13785.350000
75%    128.395000  147.500000  18278.600000
max    143.560000  200.000000  28712.000000

In [127]:
df3

  symbol   price  quantity   volume
0   orcl  123.34       120  14800.8
1   msft   98.23       130  12769.9
2    ibm   64.93        90   5843.7
3  goggl  143.56       200  28712.0

In [128]:
df4 = df3.T

In [129]:
df4

                0        1       2        3
symbol       orcl     msft     ibm    goggl
price      123.34    98.23   64.93   143.56
quantity      120      130      90      200
volume    14800.8  12769.9  5843.7  28712.0

In [130]:
df3

  symbol   price  quantity   volume
0   orcl  123.34       120  14800.8
1   msft   98.23       130  12769.9
2    ibm   64.93        90   5843.7
3  goggl  143.56       200  28712.0

In [131]:
type(df3['price'].values)

numpy.ndarray

In [132]:
'symbol' in df3.columns

True

In [133]:
3 in df3.index

True

In [134]:
df3.index

RangeIndex(start=0, stop=4, step=1)

In [135]:
10 in df3.index

False

In [136]:
ts4 = pd.Series(['blue', 'purple', 'yellow', 'green'], index=[0,2,4,6])

In [137]:
ts4

0      blue
2    purple
4    yellow
6     green
dtype: str

In [138]:
ts4.reindex([0,1,2,3,4,5,6], method='ffill') # forward fill

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
6     green
dtype: str

In [139]:
df5 = pd.DataFrame(np.arange(9).reshape((3,3)), index=['a', 'c','d'],
                   columns=['turkey', 'france', 'italy'])

In [140]:
df5

   turkey  france  italy
a       0       1      2
c       3       4      5
d       6       7      8

In [141]:
df6 = df5.reindex(['a', 'b','c','d'])

In [142]:
df6

   turkey  france  italy
a     0.0     1.0    2.0
b     NaN     NaN    NaN
c     3.0     4.0    5.0
d     6.0     7.0    8.0

In [143]:
# float('nan'), np.nan

In [144]:
df7 = df6.reindex(columns=['turkey', 'italy', 'japan'])

In [145]:
df7

   turkey  italy  japan
a     0.0    2.0    NaN
b     NaN    NaN    NaN
c     3.0    5.0    NaN
d     6.0    8.0    NaN

In [146]:
df6.drop('france',axis=1,inplace=True)

In [147]:
df6

   turkey  italy
a     0.0    2.0
b     NaN    NaN
c     3.0    5.0
d     6.0    8.0